### ISSUE TITLE
npm run dev和npm run build都出现错误

### ISSUE THREAD

**Issue by fish2016** [github1586/nuxt-bnhcp#10]
`DJdeMacBook-Pro:nuxt-bnhcp dj$ npm run dev

> bnhcp@1.0.0 dev /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp
> backpack dev

(node:4114) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                             22:14:20

This relative module was not found:

* ./api in ./server/index.js
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/build/main.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
^CDJdeMacBook-Pro:nuxt-bnhcp dj$ npm run build

> bnhcp@1.0.0 build /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp
> nuxt build

[nuxt] Building...
  nuxt:build App root: /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp +0ms
  nuxt:build Generating /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/.nuxt files... +0ms
  nuxt:build Generating files... +4ms
  nuxt:build Generating routes... +3ms
  nuxt:build Building files... +22ms
Build completed in 5.094s

[nuxt:build:client]
 Hash: 07c1a51514e61299c902
Version: webpack 2.7.0
Time: 5099ms
                                Asset       Size  Chunks             Chunk Names
vendor.bundle.d585a68383e74ba803c7.js     202 kB       0  [emitted]  vendor
  nuxt.bundle.c2ebf0d06e1049ba5410.js    1.83 kB       1  [emitted]  app
     manifest.07c1a51514e61299c902.js    1.46 kB       2  [emitted]  manifest
                           index.html  132 bytes          [emitted]  
                 client-manifest.json    12.2 kB          [emitted]  

ERROR in ./.nuxt/client.js
Module build failed: Error: Couldn't find preset "vue-app" relative to directory "/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/.nuxt"
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/babel-loader/lib/index.js:175:20)
Error: Webpack build exited with errors
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/dist/nuxt.js:1170:46
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:272:15
    at Compiler.emitRecords (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:367:37)
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:265:12
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:360:11
    at next (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:357:8)
    at Compiler.<anonymous> (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:352:14)
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/async/dist/async.js:998:13)
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/async/dist/async.js:906:16
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/eslint/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/dj/WorkSpace/GitSpace/09_26/nuxt-bnhcp/node_modules/nuxt/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bnhcp@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bnhcp@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dj/.npm/_logs/2017-09-26T14_14_40_765Z-debug.log
DJdeMacBook-Pro:nuxt-bnhcp dj$ 
DJdeMacBook-Pro:nuxt-bnhcp dj$ 
`

**Comment by github1586** [comment]
@fish2016 cd local/template 去这个里面npm install 然后npm run dev
这个里面有api文件夹 都是本地写死的数据~
