### ISSUE TITLE
请教一下，npm run dev报错？检查路径发现确实没有这个build\main.js

### ISSUE THREAD

**Issue by xucasio** [github1586/nuxt-bnhcp#21]
ERROR  Failed to compile with 1 errors15:38:52

This relative module was not found:

* ./api in ./server/index.js
module.js:491
    throw err;
    ^

Error: Cannot find module 'F:\nodes\nuxt-bnhcp\build\main.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by xucasio** [comment]
已找到解决了，谢谢

**Comment by nicewft** [comment]
你怎么解决的，兄die，我也碰到了，nuxt-koa启动报这个错
